# Generated by Django 6.0.3 on 2026-05-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_accesorio_vehiculo_accesorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('manager', 'Manager'), ('admin', 'Administrador')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='compravehiculo',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
